Random_Bakes/MainPage/urls.py
from django.urls import path
from django.conf.urls import url, include
from MainPage import views
# from Recipes import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
# from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns = [
    path('project/', views.ProjectListView.as_view(), name = 'projects'),
    path('shopping/', views.shopping, name = 'shopping'),
    # path('batch/', views.batch, name = 'batch'),
    path('contact/', views.contact, name = 'contact'),
    path('license/', views.LicenseListView.as_view(), name = 'license'),
    path('success/', views.success, name = 'success'),
    path('ACsuccess/', views.ACsuccess, name = 'ACsuccess'),
    path('sanitation/', views.SanitationListView.as_view(), name = 'sanitation'),
    path('RBs/', views.RBsListView.as_view(), name = 'RBs'),
    path('friends&family/', views.order, name = 'friends&family'),
    path('special_orders/', views.special_order, name = 'special_order'),
    path('tickets/', views.TicketListView, name = 'tickets'),
    path('trays/', views.TrayListView, name = 'trays'),
    # path('tickets/', views.TicketListView.as_view(), name = 'tickets'),
    path('orders/', views.DeliveryView.as_view(), name = 'orders'),
    url(r'^orders/(?P<pk>\d+)/detail/$', views.OrdersDetailView.as_view(), name='order_detail'),
    url(r'^orders/(?P<pk>\d+)/edit/$', views.OrdersUpdateView.as_view(), name='orders_update'),
    path('send_text/', views.send_text, name ='text_it'),
    path('registration/', views.registration, name = 'registration'),
    path('orderplaced/', views.orderplaced, name = 'orderplaced'),
    url(r'^user_login/$', views.user_login, name = 'user_login' ),
    url(r'route', views.setRoute, name='set_route'),
    url(r'^enter_batch/$', views.enterbatch, name = 'enter_batch' ),
    url(r'^thankyou/$', views.thankyou, name = 'thankyou' ),
    url(r'^TYnew/$', views.TYnew, name = 'TYnew' ),
    url(r'^about/$', views.AboutUsListView.as_view(), name ='about'),
    url(r'^customers/$', views.CustomersListView.as_view(), name ='customers'),
    url(r'^customers/(?P<pk>\d+)/edit/$', views.CustomersUpdateView.as_view(), name='customers_update'),
    url(r'^customers/new/$', views.CustomersCreateView.as_view(), name='customer_new'),
    url(r'^featurette/(?P<pk>\d+)$', views.FeaturetteDetailView.as_view(), name = 'featurette_detail'),
    url(r'^featurette/list/$', views.FeaturetteListView.as_view(), name='featurette_list'),
    url(r'^featurette/new/$', views.FeaturetteCreateView.as_view(), name='featurette_new'),
    url(r'^featurette/(?P<pk>\d+)/edit/$', views.FeaturetteUpdateView.as_view(), name='featurette_update'),
    url(r'^featurette/(?P<pk>\d+)/remove/$', views.FeaturetteDeleteView.as_view(), name='featurette_remove'),
#~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+#
    # url(r'^ActiveSales/(?P<batch>\d+)$', views.ActiveSalesDetailView.as_view(), name = 'ActiveSales_detail'),
    url(r'^ActiveSales/list/$', views.ActiveSalesListView.as_view(), name='ActiveSales_list'),
    url(r'^ActiveSales/new/$', views.ActiveSalesCreateView.as_view(), name='ActiveSales_new'),
    url(r'^ActiveSales/(?P<pk>\d+)/edit/$', views.ActiveSalesUpdateView.as_view(), name='ActiveSales_update'),
    url(r'^ActiveSales/(?P<pk>\d+)/remove/$', views.ActiveSalesDeleteView.as_view(), name='ActiveSales_remove'),
    path('email/', views.email, name = 'email'),
    # url(r'^Recipes/', include('Recipes.urls')),
    ] # + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# TEMPLATE TAGGING
app_name = 'Baking'

Random_Bakes/Random_Bakes/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from MainPage import views
import Recipes.views
from django.conf import settings
from django.conf.urls.static import static

# from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    path('admin/', admin.site.urls),
    url(r'^logout/$', views.user_logout, name = 'logout'),
    url(r'friends&family/', views.order, name = 'friends&family'),
    url(r'^user_login/$', views.user_login, name = 'user_login' ),
    url(r'^Baking/', include('MainPage.urls')),
    url(r'^Recipes/', include('Recipes.urls')),
    ]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Random_Bakes/Recipes/urls.py
from django.conf.urls import url
from django.urls import path
from Recipes import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns = [

    # path('batch_enter/', views.BatchCreateView.as_view(), name = 'batch_enter'),
    # path('batch/', views.batch_enter, name = 'batch'),
    # path('contact/', views.contact, name = 'contact'),
    # path('license/', views.LicenseListView.as_view(), name = 'license'),
    # path('Recipe/success/', views.recipe_success, name = 'recipe_success'),
    # # path('sanitation/', views.SanitationListView.as_view(), name = 'sanitation'),
    # path('order/', views.order, name = 'order'),
    # path('registration/', views.registration, name = 'registration'),
    # url(r'^user_login/$', views.user_login, name = 'user_login' ),
    # url(r'^enter_batch/$', views.enterbatch, name = 'enter_batch' ),
    # url(r'^thankyou/$', views.thankyou, name = 'thankyou' ),
    # url(r'^about/$', views.AboutUsListView.as_view(), name ='about'),
    # url(r'^featurette/(?P<pk>\d+)$', views.FeaturetteDetailView.as_view(), name = 'featurette_detail'),
    # url(r'^featurette/list/$', views.FeaturetteListView.as_view(), name='featurette_list'),
    # url(r'^featurette/new/$', views.FeaturetteCreateView.as_view(), name='featurette_new'),
    # url(r'^featurette/(?P<pk>\d+)/edit/$', views.FeaturetteUpdateView.as_view(), name='featurette_update'),
    # url(r'^featurette/(?P<pk>\d+)/remove/$', views.FeaturetteDeleteView.as_view(), name='featurette_remove'),
    ] # + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# TEMPLATE TAGGING
app_name = 'Recipes'

Random_Bakes/templates/MainApp-deleteMe/about.html
<!DOCTYPE html>
{% extends "MainApp/base.html" %}
{% block body_block %}
<!-- _______________________________________________________________________ -->
{% load static %}
  <div class="jumbotron text-dark ">
    <h1> About us</h1>
    {% for content in aboutUs %}
    <div class="container">
      <h3>{{content.title|safe|}}</h3>
      <p class ='text-left'>{{content.description|safe|linebreaks}}</p>
    </div>
  </div>
<!-- _______________________________________________________________________ -->
{% endblock %}

Random_Bakes/templates/MainApp-deleteMe/base_old.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.1.1">
    <title>Random Bakes</title>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

    <!-- Bootstrap core CSS -->
    <link href="{% static "/assets/dist/css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "/css/cover.css" %}" rel="stylesheet">
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }
      /* @import url('https://fonts.googleapis.com/css2?family=Homemade+Apple&display=swap'); */
      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
</head>
  <body class="text-center" >
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <header class="masthead mb-auto">

      <!-- <img src="{% static "/media/Random_Bakes_white.png" %}" class = "navbar-brand" alt="Logo"> -->
      <nav class="nav nav-masthead justify-content-center">
        <!-- <a class="nav-link active" href="{% url 'index' %}">Home</a>
        <a class="nav-link active" href="{% url 'Baking:projects' %}">Projects</a>  -->
      <!--
        <a class="nav-link active" href="{% url 'Baking:about' %}">About Us</a>
        <a class="nav-link" href="{% url 'Baking:registration' %}">Contact</a>
        {% if user.is_authenticated %}
        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        {% else %}
        <a class="nav-link" href="{% url 'user_login' %}">Login</a>
        {% endif %}
      </nav>
    </div> -->
  <!-- #~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+# -->
<a href="{% url 'index' %}"><img src="{% static "/media/Random_Bakes_white.png" %}" class = "navbar-brand d-flex w-75 h-auto p-1 mx-auto flex-column" alt="Logo"></a>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <!-- <a class="navbar-brand" href="#">Expand at md</a> -->

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample04" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExample04">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'Baking:projects' %}">Projects<span class="sr-only">(current)</span></a>
      </li>
      <!-- <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li> -->
      {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        <!-- <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a> -->
      </li>
      {% else %}
      <li class="nav-item">
      <a class="nav-link" href="{% url 'user_login' %}">Login</a>
    </li>
      {% endif %}

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
        <div class="dropdown-menu" aria-labelledby="dropdown04">
          <a class="dropdown-item" href="{% url 'Baking:about' %}">About Us</a>
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Contact Us</a>
          <a class="dropdown-item" href="{% url 'Baking:sanitation' %}">Sanitation Protocols</a>
          {% if user.is_authenticated %}
          <a  class="dropdown-item" href="{% url 'admin:index'  %}">Admin</a>
          {% endif %}
        </div>
      </li>
    </ul>
    <form class="form-inline my-2 my-md-0">
      <input class="form-control" type="text" placeholder="Search">
    </form>
  </div>
</nav>
<!-- #~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+# -->
  </header>
<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
{% block body_block %}
{% endblock %}
</div>
<!-- <div class="inner"> -->
  <footer class="footer d-flex ">
      <div class="container ">
                   <!-- <a href="https://getbootstrap.com/">Bootstrap</a>, by <a href="https://twitter.com/mdo">@mdo</a>.</p> -->
          &copy; 2020 Random Bakes &middot;
          <a  href="{% url 'Baking:license' %}">Licenses</a> &middot; <a  href="{% url 'Baking:sanitation' %}">Sanitation Protocols</a>

      </div>
  </footer>
<!-- </div> -->
<!-- Bootstrap core JavaScript
   ================================================== -->
   <!-- Placed at the end of the document so the pages load faster -->
   <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
   <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
   <script src="../../assets/js/vendor/popper.min.js"></script>
   <script src="../../dist/js/bootstrap.min.js"></script>
</body>
</html>

Random_Bakes/templates/MainApp-deleteMe/batch.html
<!DOCTYPE html>
{% extends "MainApp/base.html" %}
{% block body_block %}
<!-- _______________________________________________________________________ -->
{% load static %}
  <div class="jumbotron text-dark ">
    <h1>Batch</h1>
      <p>Info goes here.</p>
  </div>
<!-- _______________________________________________________________________ -->
{% endblock %}

Random_Bakes/templates/MainApp-deleteMe/contact.html
<!DOCTYPE html>
{% extends "MainApp/base.html" %}
{% block body_block %}
<!-- _______________________________________________________________________ -->
{% load static %}
  <div class="jumbotron text-dark ">
    <h1> Contact Information </h1>
      <p>Info goes here.</p>
  </div>
<!-- _______________________________________________________________________ -->
{% endblock %}

Random_Bakes/templates/MainApp-deleteMe/enter_batch.html
<!doctype html>

{% extends "MainApp/base.html" %}
{% block body_block %}
<div class="jumbotron text-dark">
  {% if formfilled %}
    <h1> Thank you for submitting new Batch info!</h1>
  {% else %}
  <h1>Enter Batch Information Here</h1>
  <h3>Fill out the form</h3>
  <form enctype="multipart/form-data"  method="post">



    {% csrf_token %}
<div class="form-row">


    
      {{batch_form.as_p }}

</div>

    <input type="submit" class= "btn btn-lg" value="Save Batch Information">

  </form>

  {% endif %}
</div>
{% endblock %}

Random_Bakes/templates/MainApp-deleteMe/index.html
<!doctype html>

{% extends "MainApp/base.html" %}
{% block body_block %}
<!-- _______________________________________________________________________ -->
{% load static %}

{% load py_functions %}
<div class="cover-container">
  <main role="main" class="inner cover">
    <img src=  "{{CoverPhoto}}"  class = "img-fluid" alt="{{ CoverAltText }}">
    <h1 class="cover-heading ">{{ CoverTitle }}</h1>
    <p class="lead">{{ CoverText }}</p>

    <p class="lead">
      <!-- <a class="btn btn-lg btn-primary lightbox-202426957335055 cover-heading" style="margin-top: 16px" >{{CoverButton}}</a> -->
      <a class="{{CoverButtonClass}}" href="{{CoverButtonLink}}" role="button">{{CoverButton}}</a>
    </p>

</div>
{% if Featurette %}
<div class="container">
  <!-- START THE FEATURETTES -->
  {% for feature in Featurette %}
  {%if forloop.counter|divisibleby:2 %}

    <div class="row featurette featurette2-container">
      <hr class="featurette-divider ">
      <div class="col-md-7 order-md-2">
        <h2 class="featurette-heading"> &middot; {{ feature.title }} &middot;</h2>
        <H3><span class="text-muted">{{ feature.subtitle }}</span></h3>
        <p class="lead text-justify">{{ feature.description|escape }}</p>
      </div>
      <div class="col-md-5 order-md-1">
        {% if feature.photo.url %}
        <img src=  "{{feature.photo.url}}"  class = "featurette-image img-fluid mx-auto" alt="Feature Photo" width="500" height="500">
        {% else %}
        <svg class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 500x500"><title>Placeholder</title><rect width="100%" height="100%" fill="#eee"/><text x="50%" y="50%" fill="#aaa" dy=".3em">500x500</text></svg>
        {% endif %}
      </div>
    </div>
    <hr class="featurette-divider ">

  {% else %}
  <div class="row featurette featurette1-container col-sm-4">
    <div class="col-md-7">
      <h2 class="featurette-heading">&middot; {{ feature.title }} &middot;</H2>
      <h3><span class="text-muted">{{ feature.subtitle }}</span></h3>
      <p class="lead text-justify"> {{feature.description}} </p>
    </div>
    <div class="col-md-5">
      <!--  -->
      <img src=  "{{feature.photo.url}}"  class = "featurette-image img-fluid mx-auto" alt="Feature Photo" width="500" height="500">

    </div>
  </div>

  <hr class="featurette-divider">
 {% endif %}
 {% endfor %}

  </div>
    <!-- /END THE FEATURETTES -->
{% endif %}
</main>
<!-- _______________________________________________________________________ -->
{% endblock %}

Random_Bakes/templates/MainApp-deleteMe/index_old.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.1.1">
    <title>RandomBakes | Home</title>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

    <!-- Bootstrap core CSS -->
    <link href="{% static "/assets/dist/css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "/css/cover.css" %}" rel="stylesheet">
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }
      /* @import url('https://fonts.googleapis.com/css2?family=Homemade+Apple&display=swap'); */
      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->

  </head>
  <body class="text-center" >
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <header class="masthead mb-auto">
    <div class="inner">
      <img src="{% static "/media/Random_Bakes_white.png" %}" class = "masthead-brand" alt="Logo">
      <nav class="nav nav-masthead justify-content-center">
        <a class="nav-link active" href="{% url 'index' %}">Home</a>
        <a class="nav-link active" href="{% url 'Baking:projects' %}">Projects</a>
        <a class="nav-link active" href="{% url 'Baking:batch' %}">Batch Info</a>
        <a class="nav-link active" href="{% url 'Baking:about' %}">About Us</a>
        <a class="nav-link" href="{% url 'Baking:sanitation' %}">Contact</a>
      </nav>
    </div>
  </header>
<!-- _______________________________________________________________________ -->
<div class="cover-container">
  <main role="main" class="inner cover">
    <img src= "{%static 'media/' %}{{ CoverPhoto }}" class = "img-fluid" alt="{{ CoverAltText}}">
    <h1 class="cover-heading">{{ CoverTitle }}</h1>
    <p class="lead">{{ CoverText }}</p>
    <p class="lead">
      <a href="{{CoverButtonLink}}" class="btn btn-lg btn-primary">{{CoverButton}}</a>
    </p>
  </main>
</div>
<!-- _______________________________________________________________________ -->
  <footer class="container">
      <div class="cite">
                   <!-- <a href="https://getbootstrap.com/">Bootstrap</a>, by <a href="https://twitter.com/mdo">@mdo</a>.</p> -->
          &copy; 2020 Random Bakes  &middot; <a  href="..\Licenses.html">Licenses</a> &middot; <a  href="..\Sanitation">Sanitation Protocols</a>
      </div>
  </footer>
</div>

</body>
</html>

Random_Bakes/templates/MainApp-deleteMe/license.html
<!DOCTYPE html>
{% extends "MainApp/base.html" %}
{% block body_block %}
<!-- _______________________________________________________________________ -->
{% load static %}
  <div class="jumbotron text-dark ">
    <h1>License Information Goes Here</h1>
      <p>Info goes here.</p>
  </div>
<!-- _______________________________________________________________________ -->
{% endblock %}

Random_Bakes/templates/MainApp-deleteMe/order.html
<!DOCTYPE html>
{% extends "MainApp/base.html" %}
{% block body_block %}
<!-- _______________________________________________________________________ -->
{% load static %}
<script src ="https://form.jotform.com/static/feedback2.js" type="text/javascript"></script><script type="text/javascript">
    var JFL_202426957335055 = new JotformFeedback({
      formId: '202426957335055',
      base: 'https://form.jotform.com/',
      windowTitle: 'Bagel Order Form',
      background: '#FFA500',
      fontColor: '#FFFFFF',
      type: 'false',
      height: 500,
      width: 700,
      openOnLoad: false
    });
</script>
<div class="cover-container">
  <main role="main" class="inner cover">
    <img src=  "{{CoverPhoto}}"  class = "img-fluid" alt="{{ CoverAltText }}">
    <h1 class="cover-heading ">{{ CoverTitle }}</h1>
    <p class="lead">{{ CoverText }}</p>
    <p class="lead">Bagels available this week: {{ BagelsAvailable }}  |  Bagels sold this week: {{ BagelsSold }}</p>
      <p class="lead">{{DeliveryInfo}}</p>
    <p class="lead">
      <a class="{{CoverButtonClass}}" href="{{CoverButtonLink}}" style="margin-top: 16px" >{{CoverButton}}</a>
    </p>
  </main>
</div>
  <!-- <div class="container">
    <script src ="https://form.jotform.com/static/feedback2.js" type="text/javascript"></script><script type="text/javascript">
        var JFL_202426957335055 = new JotformFeedback({
          formId: '202426957335055',
          base: 'https://form.jotform.com/',
          windowTitle: 'Bagel Order Form',
          background: '#FFA500',
          fontColor: '#FFFFFF',
          type: 'false',
          height: 500,
          width: 700,
          openOnLoad: false
        });
    </script>
      <a class="btn lightbox-202426957335055" style="margin-top: 16px">
        Bagel Order Form
      </a> -->

<!-- _______________________________________________________________________ -->
{% endblock %}

Random_Bakes/templates/MainApp-deleteMe/registration.html
<!doctype html>

{% extends "MainApp/base.html" %}
{% block body_block %}
<div class="jumbotron text-dark">
  {% if registered %}
    <h1> Thank you for registering</h1>
  {% else %}
  <h1>Register Here</h1>
  <h3>Fill out the form</h3>
  <form class = "form-group" enctype="multipart/form-data" method="post" >
    {% csrf_token%}
    {{user_form.as_p }}
    {{profile_form.as_p}}
    <input type="submit" value="Register">
  </form>
  {% endif %}
</div>
{% endblock %}

Random_Bakes/templates/MainApp-deleteMe/sanitation.html
<!DOCTYPE html>
{% extends "MainApp/base.html" %}
{% block body_block %}
<!-- _______________________________________________________________________ -->
{% load static %}
  <div class="jumbotron text-dark ">
    <h1> Sanitation Information</h1>
      <p>{{test_injection}}</p>
  </div>
<!-- _______________________________________________________________________ -->
{% endblock %}

Random_Bakes/templates/MainApp-deleteMe/thankyou.html
<!DOCTYPE html>
{% extends "MainApp/base.html" %}
{% block body_block %}
<!-- _______________________________________________________________________ -->
{% load static %}
  <div class="jumbotron text-dark ">
    <h1> Thank You</h1>
      <p>{{BATCH_ID}}</p>
      <p>{{Customer}}</p>
  </div>
<!-- _______________________________________________________________________ -->
{% endblock %}

Random_Bakes/templates/MainApp-deleteMe/user_login.html
<!DOCTYPE html>
{% extends "MainApp/base.html" %}
{% block body_block %}

<div class="jumbotron text-dark">
  <h1>Please Login</h1>
  <form  action="{% url 'Baking:user_login' %}" method="post">
    {% csrf_token %}
    <label for="username">UserName:</label>
    <input type="text" name="username" class="form-control"placeholder="Enter Username">

    <label for="password">Password</label>
    <input type="password" class="form-control" name="password">

    <input type="submit" class= "btn btn-lg" value="Login">
  </form>
</div>

{% endblock %}