Random_Bakes/MainPage/urls.py
from django.urls import path
from django.conf.urls import url, include
from MainPage import views
# from Recipes import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
# from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns = [
    path('project/', views.ProjectListView.as_view(), name = 'projects'),
    path('shopping/', views.shopping, name = 'shopping'),
    # path('batch/', views.batch, name = 'batch'),
    path('contact/', views.contact, name = 'contact'),
    path('license/', views.LicenseListView.as_view(), name = 'license'),
    path('success/', views.success, name = 'success'),
    path('ACsuccess/', views.ACsuccess, name = 'ACsuccess'),
    path('sanitation/', views.SanitationListView.as_view(), name = 'sanitation'),
    path('RBs/', views.RBsListView.as_view(), name = 'RBs'),
    path('friends&family/', views.order, name = 'friends&family'),
    path('special_orders/', views.special_order, name = 'special_order'),
    path('tickets/', views.TicketListView, name = 'tickets'),
    path('trays/', views.TrayListView, name = 'trays'),
    # path('tickets/', views.TicketListView.as_view(), name = 'tickets'),
    path('orders/', views.DeliveryView.as_view(), name = 'orders'),
    url(r'^orders/(?P<pk>\d+)/detail/$', views.OrdersDetailView.as_view(), name='order_detail'),
    url(r'^orders/(?P<pk>\d+)/edit/$', views.OrdersUpdateView.as_view(), name='orders_update'),
    path('send_text/', views.send_text, name ='text_it'),
    path('registration/', views.registration, name = 'registration'),
    path('orderplaced/', views.orderplaced, name = 'orderplaced'),
    url(r'^user_login/$', views.user_login, name = 'user_login' ),
    url(r'route', views.setRoute, name='set_route'),
    url(r'^enter_batch/$', views.enterbatch, name = 'enter_batch' ),
    url(r'^thankyou/$', views.thankyou, name = 'thankyou' ),
    url(r'^TYnew/$', views.TYnew, name = 'TYnew' ),
    url(r'^about/$', views.AboutUsListView.as_view(), name ='about'),
    url(r'^customers/$', views.CustomersListView.as_view(), name ='customers'),
    url(r'^customers/(?P<pk>\d+)/edit/$', views.CustomersUpdateView.as_view(), name='customers_update'),
    url(r'^customers/new/$', views.CustomersCreateView.as_view(), name='customer_new'),
    url(r'^featurette/(?P<pk>\d+)$', views.FeaturetteDetailView.as_view(), name = 'featurette_detail'),
    url(r'^featurette/list/$', views.FeaturetteListView.as_view(), name='featurette_list'),
    url(r'^featurette/new/$', views.FeaturetteCreateView.as_view(), name='featurette_new'),
    url(r'^featurette/(?P<pk>\d+)/edit/$', views.FeaturetteUpdateView.as_view(), name='featurette_update'),
    url(r'^featurette/(?P<pk>\d+)/remove/$', views.FeaturetteDeleteView.as_view(), name='featurette_remove'),
#~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+#
    # url(r'^ActiveSales/(?P<batch>\d+)$', views.ActiveSalesDetailView.as_view(), name = 'ActiveSales_detail'),
    url(r'^ActiveSales/list/$', views.ActiveSalesListView.as_view(), name='ActiveSales_list'),
    url(r'^ActiveSales/new/$', views.ActiveSalesCreateView.as_view(), name='ActiveSales_new'),
    url(r'^ActiveSales/(?P<pk>\d+)/edit/$', views.ActiveSalesUpdateView.as_view(), name='ActiveSales_update'),
    url(r'^ActiveSales/(?P<pk>\d+)/remove/$', views.ActiveSalesDeleteView.as_view(), name='ActiveSales_remove'),
    path('email/', views.email, name = 'email'),
    # url(r'^Recipes/', include('Recipes.urls')),
    ] # + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# TEMPLATE TAGGING
app_name = 'Baking'

Random_Bakes/Random_Bakes/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from MainPage import views
import Recipes.views
from django.conf import settings
from django.conf.urls.static import static

# from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    path('admin/', admin.site.urls),
    url(r'^logout/$', views.user_logout, name = 'logout'),
    url(r'friends&family/', views.order, name = 'friends&family'),
    url(r'^user_login/$', views.user_login, name = 'user_login' ),
    url(r'^Baking/', include('MainPage.urls')),
    url(r'^Recipes/', include('Recipes.urls')),
    ]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Random_Bakes/Recipes/urls.py
from django.conf.urls import url
from django.urls import path
from Recipes import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns = [

    # path('batch_enter/', views.BatchCreateView.as_view(), name = 'batch_enter'),
    # path('batch/', views.batch_enter, name = 'batch'),
    # path('contact/', views.contact, name = 'contact'),
    # path('license/', views.LicenseListView.as_view(), name = 'license'),
    # path('Recipe/success/', views.recipe_success, name = 'recipe_success'),
    # # path('sanitation/', views.SanitationListView.as_view(), name = 'sanitation'),
    # path('order/', views.order, name = 'order'),
    # path('registration/', views.registration, name = 'registration'),
    # url(r'^user_login/$', views.user_login, name = 'user_login' ),
    # url(r'^enter_batch/$', views.enterbatch, name = 'enter_batch' ),
    # url(r'^thankyou/$', views.thankyou, name = 'thankyou' ),
    # url(r'^about/$', views.AboutUsListView.as_view(), name ='about'),
    # url(r'^featurette/(?P<pk>\d+)$', views.FeaturetteDetailView.as_view(), name = 'featurette_detail'),
    # url(r'^featurette/list/$', views.FeaturetteListView.as_view(), name='featurette_list'),
    # url(r'^featurette/new/$', views.FeaturetteCreateView.as_view(), name='featurette_new'),
    # url(r'^featurette/(?P<pk>\d+)/edit/$', views.FeaturetteUpdateView.as_view(), name='featurette_update'),
    # url(r'^featurette/(?P<pk>\d+)/remove/$', views.FeaturetteDeleteView.as_view(), name='featurette_remove'),
    ] # + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# TEMPLATE TAGGING
app_name = 'Recipes'

Random_Bakes/MainPage/views.py
from django.shortcuts import render, get_object_or_404, redirect
from MainPage.models import (highlight,
                             ActiveSales,
                             Featurette,
                             Orders,
                             Customer, 
                             Subscription, 
                             Notices)
from django.utils import timezone
from MainPage.forms import (UserForm,
                            UserProfileInfoForm,
                            ActiveSalesForm,
                            AS_Create_Form,
                            FeaturetteForm, 
                            OrdersForm,
                            CustomerForm)
from check_inventory import ProcessSales
from check_inventory import route 
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.views.generic import (View,
                                  TemplateView,
                                  ListView,
                                  DetailView,
                                  CreateView,
                                  UpdateView,
                                  DeleteView)
from django.views.generic.edit import FormMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.decorators.http import require_http_methods
from django.views.decorators.csrf import csrf_exempt
from datetime import date, datetime,timedelta
from django.db.models.functions import Now
from config import sendtext
import ast, re
from django.core.mail import send_mail
import secret_key

# Create your views here.
@require_http_methods(["GET", "POST"])
def orderplaced(request):
    print(request.GET.get('id', None))
    print("Worked")
    return HttpResponse("Order Placed!")

def index(request):
    B_info = BatchInfo()
    today = date.today()
    cover_content2 = highlight.objects.filter(title = "Order Bagels")[0]
    feat = Featurette.objects.filter(type = 'index').order_by("order")
    notice = Notices.objects.filter(type = 'index', active = "True")
    sold = ProcessSales()
    totsold = sold['totBagels']
    story = cover_content2.story
    story = story.replace('[[units]]', str(B_info[0]))
    if B_info[1]: #this indicates that the batch is sold out
        buttonText = "Sold Out!"
        buttonLink = "#" #Eventially take to batch info for previous batch.
    elif not B_info[2]:
        buttonText = "Sales Not Open Yet"
        buttonLink = "#"
    else:
        buttonText = cover_content2.button
        buttonLink = cover_content2.button_link
    cover_content ={'CoverTitle': cover_content2.title,
           'CoverText': story,
           'CoverPhoto': cover_content2.photo2.url,
           'CoverAltText': cover_content2.photo_alt,
           'CoverButton': buttonText,
           'CoverButtonLink': buttonLink,
           'CoverButtonClass': cover_content2.button_class,
           'CoverScript': cover_content2.script,
           'Featurette': feat,
           'TotalSold': totsold, 
           'NextSaleOpen':B_info[3], 
           'Notices': notice,
           'RB': B_info[4], 
           'LastBaked': B_info[5]}
    return render(request,'MainPage/index.html', context = cover_content)


def setRoute(request):
    try:
        invt = ActiveSales.objects.get(delivery ="True")
        return redirect(route(invt.id))
    except: 
        web = 'MainPage/index.html'
    return render(request, web)

def projects(request):
    return render(request,'MainPage/projects.html')

class AboutUsListView(ListView):
    template_name = 'MainPage/blank_content.html'
    queryset = Featurette.objects.filter(type='About Us')
    context_object_name = 'articles'
    ordering = ['order']

class SanitationListView(ListView):
    template_name = 'MainPage/blank_content.html'
    queryset = Featurette.objects.filter(type = 'Sanitation Protocols')
    context_object_name = 'articles'
    ordering = ['order']

class RBsListView(ListView):
    template_name = 'MainPage/blank_content.html'
    queryset = Featurette.objects.filter(type = 'Projects')
    context_object_name = 'articles'
    ordering = ['order']

class LicenseListView(ListView):
    template_name = 'MainPage/blank_content.html'
    queryset = Featurette.objects.filter(type='Licenses')
    context_object_name = 'articles'
    ordering = ['order']
#~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+#
class ProjectListView(ListView):
    template_name = 'MainPage/blank_content.html'
    queryset = Featurette.objects.filter(type='Projects')
    context_object_name = 'articles'
    ordering = ['order']

class FeaturetteListView(ListView):
    model = Featurette

class ActiveSalesListView(ListView):
    model = ActiveSales
    template_name = 'MainPage/batches.html'
    queryset = ActiveSales.objects.all()
    context_object_name = 'batches'
    ordering = ['-end_sales']

# class TicketListView(ListView):
#     template_name = 'MainPage/tickets.html'
#     acv_sales = ActiveSales.objects.get(active = "True")
#     queryset = Orders.objects.filter(batch = acv_sales.id)
#     context_object_name = 'tickets'
#     ordering= ['customer']
def BuildTicket(tickets):
    for ticket in tickets:
        ordered = {}
        if ticket.Plain_sold > 0:
            ordered['Plain'] = int(ticket.Plain_sold)
        if ticket.Sesame_sold > 0:
            ordered['Sesame'] = ticket.Sesame_sold            
        if ticket.Salt_sold > 0:
            ordered['Salt'] = ticket.Salt_sold
        if ticket.Onion_sold > 0:
            ordered['Onion'] = ticket.Onion_sold
        if ticket.Poppy_sold > 0:
            ordered['Poppy'] = ticket.Poppy_sold
        if ticket.Garlic_sold > 0:
            ordered['Garlic'] = ticket.Garlic_sold
        if ticket.Everything_sold > 0:
            ordered['Every'] = ticket.Everything_sold
        if ticket.RandomBake_sold > 0:
            ordered['R_Bake']= ticket.RandomBake_sold
        if ticket.CreamCheese_sold > 0:
            ordered['C_Cheese'] =  ticket.CreamCheese_sold
        if ticket.Dog_sold >0:
            ordered['Dog_T']= ticket.Dog_sold
        if ticket.EvMix_sold >0:
            ordered['Ev_Mix'] = ticket.EvMix_sold
        if ticket.AButter_sold >0:
            ordered['A_Butter'] = ticket.AButter_sold
        built = "<div><table >"
        if ticket.recipient:
            built+= '<tr><td colspan="2"><div class = "name">%s</div></td></tr>' % ticket.recipient
        else:
            built +='<tr><td colspan="2"><div class = "name">%s %s</div></td></tr>' %(ticket.customer.Fname, ticket.customer.Lname)
        built += '<tr><td colspan="2">%s</td></tr>' %ticket.deliveryinfo.replace('\n', '<br>').replace('<br><br>', '<br>').replace('Delivery Notes: None', "")[:100]
        col = 1
        for order in ordered:
            if not (col %2 )==0:
                built +="<tr><td>%s: %s </td>" %(order, ordered[order])
            else:
                built += "<td>%s: %s </td></tr>" %(order, ordered[order])
            col+=1
        if not (col %2 )==0:
            built += "<td></td></tr></table> </div>"
        else:
            built += "</table> </div>"
        ticket.ticket_text =built
        try:
                ticket.save()
        except:
            print(built)

def TicketListView(request):
    batches = ActiveSales.objects.all().order_by("-batch")
    if request.GET.get('batch'):
        acv_sales = ActiveSales.objects.get(batch = request.GET.get('batch'))
    else:
        acv_sales = ActiveSales.objects.get(active = "True")    
    tickets = Orders.objects.filter(batch = acv_sales.id).order_by('customer')
    BuildTicket(tickets)   
    return render(request,'MainPage/tickets.html', {'tickets': tickets, 
                                                    'batches': batches,
                                                    
                                                     })
def TrayListView(request):    
        
    acv_sales = ActiveSales.objects.filter(active =True)[0]
    print (acv_sales.Plain_sold)
    return render(request,'MainPage/trays.html', {'sold': acv_sales,
                                                    'plainrange': range(acv_sales.Plain_sold),
                                                     })
class OrdersListView(ListView):
    
    model = Orders
    ordering= ['-batch']

#~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+#
class FeaturetteDetailView(DetailView):
    model = Featurette

def send_text(request):
    if request.method =="POST":
        OrdId = request.POST['OrderID']
        phone = request.POST['phone']
        #deliverorder = request.POST['deliverorder']
        text = request.POST['message']
        # text = "Your Bagel order is at your front door! Thank you and enjoy! (This is an automated text!)"
        now = Now()
        # send_mail('test', 'body of the message', 'info@RandomBakes.com', ['kale@ebraden.com'])
        if (request.POST['sendText']=="Delivered"):
            if (len(phone)==11):
                status = sendtext(phone, text)
            else:
                status = "%s Number not correct length, text not sent. " %phone
        else:
            status = "Order delivered, no text notification sent."
        # try:
        #     subj = "%s Order placed!" %NewOrder.batch
        #     msg = "HUZZAH! %s %s has ordered %s" % {DjangoCustomer.Fname, DjangoCustomer.Lname, NewOrder.cart}
        #     send_mail('Order Placed', 'body of the message', 'info@RandomBakes.com', [config.KB, config.TT])
        # except:
        #     print("Email Didn't work")
        try:
            OrderTracing = Orders.objects.get(id=OrdId)
            status += " %s Delivery recorded" %(OrderTracing.batch)
            
            OrderTracing.delivered = now
            OrderTracing.delivorder= OrderTracing.delivorder+20

Random_Bakes/MainPage/templates/MainPage/ActiveSales_detail.html
<!DOCTYPE html>
{% extends "MainPage/base.html" %}
{% block body_block %}
<!-- _______________________________________________________________________ -->
{% load static %}
  <div class="container ">
    <h1>Feature: {{Batches.title}}</h1>

  </div>
<!-- _______________________________________________________________________ -->
{% endblock %}

Random_Bakes/MainPage/templates/MainPage/ActiveSales_new.html
<!DOCTYPE html>
{% extends "MainPage/base.html" %}
{% block body_block %}
<!-- _______________________________________________________________________ -->
{% load static %}
  <div class="container text-left">
    <h1>Active Sales Form</h1>
    <h2>New Active Sales Period</h2>
      <form class="post-form"  method="post" enctype="multipart/form-data">
        {%csrf_token %}
        {{form.as_p}}
        <button type="submit" class= "btn btn-sm btn-primary">Submit</button>
        <a href="javascript:history.back()" class= "btn btn-sm btn-secondary">Cancel</a>
      </form>
      <script>var editor = new MediumEditor('.editable');</script>
  </div>
<!-- _______________________________________________________________________ -->
{% endblock %}

Random_Bakes/MainPage/templates/MainPage/ActiveSales_update.html
<!DOCTYPE html>
{% extends "MainPage/base.html" %}
{% block body_block %}
<!-- _______________________________________________________________________ -->
{% load static %}
  <div class="container text-left">
    <h1>Active Sales Form</h1>
      <form class="post-form"  method="post" enctype="multipart/form-data">
        {%csrf_token %}
        {{form.as_p}}
        <button type="submit" class= "btn btn-sm btn-primary">Submit</button>
        <a href="javascript:history.back()" class= "btn btn-sm btn-secondary">Cancel</a>
      </form>
      <script>var editor = new MediumEditor('.editable');</script>
  </div>
<!-- _______________________________________________________________________ -->
{% endblock %}

Random_Bakes/MainPage/templates/MainPage/base.html
<!doctype html>
{% load static %}

<html lang="en" class = "h-100">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="Kale Braden">
  <meta name="generator" content="Jekyll v4.1.1">
  <!-- <meta property="og:title" content = "Random Bakes Cottage Bakery"> -->
  <meta property="og:description" content = "We are a Sacramento, California licensed Cottage Food bakery producing 48 bagels and other baked goods each Saturday for contactless delivery within 10 miles of the Tahoe Park neighborhood. Order online starting Monday">
  <meta property="og:image" content="{% static '/media/Cover_Bagel.png' %}">
  <meta property="og:image:type" content="image/png">
  <meta property="og:image:width" content="500">
  <meta property="og:image:height" content="502">
  <meta property="og:url" content="https://www.RandomBakes.com">
  <title> Random Bakes</title>
  <link rel="icon" href="{% static "/one_Bagle_small.png" %}" type="image/png">
  
  <link href="{% static "/assets/dist/css/bootstrap.min.css" %}" rel="stylesheet">
  <link href="{% static "/css/sticky-footer-navbar.css" %}" rel="stylesheet">
  <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
  <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script> -->
  <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
  <style>
    
/* Icon when the collapsible content is shown */
.btn2:after {
  /* font-family: "Glyphicons Halflings"; */
  content: "Less";
  float: right;
  margin-left: 10px;
}
/* Icon when the collapsible content is hidden */
.btn2.collapsed:after {
  content: "More";
}
  </style>
</head>
<body class="text-center" >
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
      <header class="masthead mb-auto">
      <nav class="nav nav-masthead justify-content-center">
        <nav class="navbar navbar-expand-xl navbar-dark bg-dark">
          <a href="\"><img src="{% static "/media/Random_Bakes_white.png" %}" class = "RandBakes " alt="Logo"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample04" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarsExample04">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                  <a class="nav-link" href="\"><span data-feather="home" class="sr-only">(current)</span></a>
                  
                </li>
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'Baking:about' %}">About Us</a>
                </li>
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'Baking:RBs' %}">RandomBaked</a>
                </li>
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'Baking:license' %}">Licenses</a>
                </li>
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'Baking:sanitation' %}">Sanitation</a>
                </li>
                <li class="nav-item active"> <a class="nav-link" href="{% url 'Baking:contact' %}">Contact Us</a></li>
                <!-- <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">More...</a>
                  <div class="dropdown-menu" aria-labelledby="dropdown04">
                    <a class="dropdown-item" href="{% url 'Baking:projects' %}">Projects<span class="sr-only">(current)</span></a>
                   
                    
                  </div>
                </li> -->
                {% if user.is_authenticated %}
                  <li>
                    <a href="{% url 'logout' %}"><span class="nav-item" data-feather="unlock"></span></a>&ThickSpace; 
                    <!-- <img src="{% static "/media/unlocked.png" %}" class = "" alt="Logout"> -->
                  </li>
                  <li>
                    <a   href="{% url 'admin:index'  %}"><span class="nav-item" data-feather="database"></span></a>&ThickSpace; 
                  </li>
                  <li>
                    <a  href="{% url 'Baking:ActiveSales_list' %}"><span class="nav-item" data-feather="calendar"></a>&ThickSpace;
                  </li> 
                  <li >
                    <a href="{% url 'Baking:orders' %}"><span class="nav-item" data-feather="truck"></a>&ThickSpace;
                  </li>
                  <li >
                    <a href="{% url 'Baking:customers' %}"><span class="nav-item" data-feather="users"></a>&ThickSpace;
                  </li>
                  <li >
                    <a href="{% url 'Baking:email' %}"><span class="nav-item" data-feather="send"></a>&ThickSpace;
                  </li>        
                {% else %}
                  <li class="nav-item inactive">
                    <a href="{% url 'user_login' %}"><span class="nav-item"data-feather="lock"></span></a>
                    <!-- <img src="{% static "/media/locked.png" %}" class = "" alt="Login"> -->
                  </li>

                {% endif %}
                 <!-- <li class = "nav-item">
                      <span class="snipcart-items-count"><button class="snipcart-checkout"></button></span>
                  </li> -->
              </ul>
            </div>
          </nav>
        </header>

<!-- #~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+# -->
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
    {% block body_block %}
    {% endblock %}
    </div>
    <!-- <div class="inner"> -->
      
      <footer class="footer mt-auto py-3 text-dark">
        &copy; 2020-2021 Random Bakes
      </footer>
 </div>
 
</body>
<!-- <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script> -->
      <!-- <script>window.jQuery || document.write('<script src="../assets/js/vendor/jquery.slim.min.js"><\/script>')</script><script src="../assets/dist/js/bootstrap.bundle.min.js"></script> -->
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
      <script src="{% static "/assets/dist/js/bootstrap.min.js" %}"></script>  
      <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>
        <script src="{% static "/assets/dist/js/dashboard.js" %}"></script></body>
</html>

Random_Bakes/MainPage/templates/MainPage/batch.html
<!DOCTYPE html>
{% extends "MainPage/base.html" %}
{% block body_block %}
<!-- _______________________________________________________________________ -->
{% load static %}
  <div class="jumbotron text-dark ">
    <h1>Batch</h1>
      <p>Info goes here.</p>
  </div>
<!-- _______________________________________________________________________ -->
{% endblock %}

Random_Bakes/MainPage/templates/MainPage/customer_form.html
<!DOCTYPE html>
{% extends "MainPage/base.html" %}
{% block body_block %}
<!-- _______________________________________________________________________ -->
{% load static %}
  <div class="container text-left">
    <h1>Customer Edit</h1>
      <form class="post-form"  method="post" enctype="multipart/form-data">
        {%csrf_token %}
        {{form.as_p}}
        <button type="submit" class= "btn btn-sm btn-primary">Submit</button>
        <a href="javascript:history.back()" class= "btn btn-sm btn-secondary">Cancel</a>
      </form>
      <script>var editor = new MediumEditor('.editable');</script>
  </div>
<!-- _______________________________________________________________________ -->
{% endblock %}

Random_Bakes/MainPage/templates/MainPage/featurette_detail.html
<!DOCTYPE html>
{% extends "MainPage/base.html" %}
{% block body_block %}
<!-- _______________________________________________________________________ -->
{% load static %}
  <div class="container ">
    <h1>Feature: {{featurette.title}}</h1>

  </div>
<!-- _______________________________________________________________________ -->
{% endblock %}